/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.ConvertResponse
import com.currencycore.sdk.models.ConvertResponseResultsInner

class ConvertResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConvertResponse
        //val modelInstance = ConvertResponse()

        // to test the property `from`
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

        // to test the property `fromCountry`
        should("test fromCountry") {
            // uncomment below to test the property
            //modelInstance.fromCountry shouldBe ("TODO")
        }

        // to test the property `requestedDate`
        should("test requestedDate") {
            // uncomment below to test the property
            //modelInstance.requestedDate shouldBe ("TODO")
        }

        // to test the property `asOf`
        should("test asOf") {
            // uncomment below to test the property
            //modelInstance.asOf shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
