/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.ConvertResponseResultsInnerPppAnyOf

class ConvertResponseResultsInnerPppAnyOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConvertResponseResultsInnerPppAnyOf
        //val modelInstance = ConvertResponseResultsInnerPppAnyOf()

        // to test the property `fromFactor`
        should("test fromFactor") {
            // uncomment below to test the property
            //modelInstance.fromFactor shouldBe ("TODO")
        }

        // to test the property `toFactor`
        should("test toFactor") {
            // uncomment below to test the property
            //modelInstance.toFactor shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

        // to test the property `source`
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

    }
}
