/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.ConvertResponseResultsInner
import com.currencycore.sdk.models.ConvertResponseResultsInnerPpp

class ConvertResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConvertResponseResultsInner
        //val modelInstance = ConvertResponseResultsInner()

        // to test the property `to`
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

        // to test the property `rate`
        should("test rate") {
            // uncomment below to test the property
            //modelInstance.rate shouldBe ("TODO")
        }

        // to test the property `toCountry`
        should("test toCountry") {
            // uncomment below to test the property
            //modelInstance.toCountry shouldBe ("TODO")
        }

        // to test the property `ppp`
        should("test ppp") {
            // uncomment below to test the property
            //modelInstance.ppp shouldBe ("TODO")
        }

    }
}
