/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.CorrelationResponseResultsInner

class CorrelationResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CorrelationResponseResultsInner
        //val modelInstance = CorrelationResponseResultsInner()

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `correlation`
        should("test correlation") {
            // uncomment below to test the property
            //modelInstance.correlation shouldBe ("TODO")
        }

        // to test the property `observations`
        should("test observations") {
            // uncomment below to test the property
            //modelInstance.observations shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
