/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.DrawdownResponseResultsInner

class DrawdownResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DrawdownResponseResultsInner
        //val modelInstance = DrawdownResponseResultsInner()

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `maxDrawdownPct`
        should("test maxDrawdownPct") {
            // uncomment below to test the property
            //modelInstance.maxDrawdownPct shouldBe ("TODO")
        }

        // to test the property `peakDate`
        should("test peakDate") {
            // uncomment below to test the property
            //modelInstance.peakDate shouldBe ("TODO")
        }

        // to test the property `troughDate`
        should("test troughDate") {
            // uncomment below to test the property
            //modelInstance.troughDate shouldBe ("TODO")
        }

        // to test the property `recoveryDate`
        should("test recoveryDate") {
            // uncomment below to test the property
            //modelInstance.recoveryDate shouldBe ("TODO")
        }

        // to test the property `recoveryDays`
        should("test recoveryDays") {
            // uncomment below to test the property
            //modelInstance.recoveryDays shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
