/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.HistoryAnalysisResponseResultsInner
import com.currencycore.sdk.models.HistoryAnalysisResponseResultsInnerStats

class HistoryAnalysisResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HistoryAnalysisResponseResultsInner
        //val modelInstance = HistoryAnalysisResponseResultsInner()

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `startDate`
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

        // to test the property `endDate`
        should("test endDate") {
            // uncomment below to test the property
            //modelInstance.endDate shouldBe ("TODO")
        }

        // to test the property `startRate`
        should("test startRate") {
            // uncomment below to test the property
            //modelInstance.startRate shouldBe ("TODO")
        }

        // to test the property `endRate`
        should("test endRate") {
            // uncomment below to test the property
            //modelInstance.endRate shouldBe ("TODO")
        }

        // to test the property `changePct`
        should("test changePct") {
            // uncomment below to test the property
            //modelInstance.changePct shouldBe ("TODO")
        }

        // to test the property `strengthenedPct`
        should("test strengthenedPct") {
            // uncomment below to test the property
            //modelInstance.strengthenedPct shouldBe ("TODO")
        }

        // to test the property `stats`
        should("test stats") {
            // uncomment below to test the property
            //modelInstance.stats shouldBe ("TODO")
        }

        // to test the property `series`
        should("test series") {
            // uncomment below to test the property
            //modelInstance.series shouldBe ("TODO")
        }

        // to test the property `volatility`
        should("test volatility") {
            // uncomment below to test the property
            //modelInstance.volatility shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
