/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.MeanReversionResponseResultsInner

class MeanReversionResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MeanReversionResponseResultsInner
        //val modelInstance = MeanReversionResponseResultsInner()

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `score`
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `deviationPct`
        should("test deviationPct") {
            // uncomment below to test the property
            //modelInstance.deviationPct shouldBe ("TODO")
        }

        // to test the property `reversionFrequency`
        should("test reversionFrequency") {
            // uncomment below to test the property
            //modelInstance.reversionFrequency shouldBe ("TODO")
        }

        // to test the property `halfLifeDays`
        should("test halfLifeDays") {
            // uncomment below to test the property
            //modelInstance.halfLifeDays shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
