/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.PppAnalysisResponseResultsInner
import com.currencycore.sdk.models.HistoryAnalysisResponseResultsInnerStats

class PppAnalysisResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PppAnalysisResponseResultsInner
        //val modelInstance = PppAnalysisResponseResultsInner()

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `startYear`
        should("test startYear") {
            // uncomment below to test the property
            //modelInstance.startYear shouldBe ("TODO")
        }

        // to test the property `endYear`
        should("test endYear") {
            // uncomment below to test the property
            //modelInstance.endYear shouldBe ("TODO")
        }

        // to test the property `startFactor`
        should("test startFactor") {
            // uncomment below to test the property
            //modelInstance.startFactor shouldBe ("TODO")
        }

        // to test the property `endFactor`
        should("test endFactor") {
            // uncomment below to test the property
            //modelInstance.endFactor shouldBe ("TODO")
        }

        // to test the property `changePct`
        should("test changePct") {
            // uncomment below to test the property
            //modelInstance.changePct shouldBe ("TODO")
        }

        // to test the property `projected`
        should("test projected") {
            // uncomment below to test the property
            //modelInstance.projected shouldBe ("TODO")
        }

        // to test the property `stats`
        should("test stats") {
            // uncomment below to test the property
            //modelInstance.stats shouldBe ("TODO")
        }

        // to test the property `series`
        should("test series") {
            // uncomment below to test the property
            //modelInstance.series shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
