/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.RatesByBaseResponsePpp

class RatesByBaseResponsePppTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RatesByBaseResponsePpp
        //val modelInstance = RatesByBaseResponsePpp()

        // to test the property `base`
        should("test base") {
            // uncomment below to test the property
            //modelInstance.base shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

        // to test the property `propertyValues`
        should("test propertyValues") {
            // uncomment below to test the property
            //modelInstance.propertyValues shouldBe ("TODO")
        }

    }
}
