/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.RatesByBaseResponse
import com.currencycore.sdk.models.RatesByBaseResponsePpp

class RatesByBaseResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RatesByBaseResponse
        //val modelInstance = RatesByBaseResponse()

        // to test the property `base`
        should("test base") {
            // uncomment below to test the property
            //modelInstance.base shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `rates`
        should("test rates") {
            // uncomment below to test the property
            //modelInstance.rates shouldBe ("TODO")
        }

        // to test the property `requestedDate`
        should("test requestedDate") {
            // uncomment below to test the property
            //modelInstance.requestedDate shouldBe ("TODO")
        }

        // to test the property `asOf`
        should("test asOf") {
            // uncomment below to test the property
            //modelInstance.asOf shouldBe ("TODO")
        }

        // to test the property `ppp`
        should("test ppp") {
            // uncomment below to test the property
            //modelInstance.ppp shouldBe ("TODO")
        }

    }
}
