/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.models.SafeHavenResponse
import com.currencycore.sdk.models.SafeHavenResponseCrisis
import com.currencycore.sdk.models.SafeHavenResponseResultsInner

class SafeHavenResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SafeHavenResponse
        //val modelInstance = SafeHavenResponse()

        // to test the property `base`
        should("test base") {
            // uncomment below to test the property
            //modelInstance.base shouldBe ("TODO")
        }

        // to test the property `from`
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `to`
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `crisis`
        should("test crisis") {
            // uncomment below to test the property
            //modelInstance.crisis shouldBe ("TODO")
        }

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

        // to test the property `universe`
        should("test universe") {
            // uncomment below to test the property
            //modelInstance.universe shouldBe ("TODO")
        }

    }
}
