/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.currencycore.sdk.models.AiResponse
import com.currencycore.sdk.models.ApiError
import com.currencycore.sdk.models.ConvertResponse
import com.currencycore.sdk.models.CorrelationResponse
import com.currencycore.sdk.models.CountriesResponseInner
import com.currencycore.sdk.models.CurrenciesResponseInner
import com.currencycore.sdk.models.DrawdownResponse
import com.currencycore.sdk.models.HistoryAnalysisResponse
import com.currencycore.sdk.models.HistoryResponse
import com.currencycore.sdk.models.MeanReversionResponse
import com.currencycore.sdk.models.PppAnalysisResponse
import com.currencycore.sdk.models.RatesByBaseResponse
import com.currencycore.sdk.models.RatesResponse
import com.currencycore.sdk.models.SafeHavenResponse
import com.currencycore.sdk.models.VolatilityResponse

import com.squareup.moshi.Json

import com.currencycore.sdk.infrastructure.ApiClient
import com.currencycore.sdk.infrastructure.ApiResponse
import com.currencycore.sdk.infrastructure.ClientException
import com.currencycore.sdk.infrastructure.ClientError
import com.currencycore.sdk.infrastructure.ServerException
import com.currencycore.sdk.infrastructure.ServerError
import com.currencycore.sdk.infrastructure.MultiValueMap
import com.currencycore.sdk.infrastructure.PartConfig
import com.currencycore.sdk.infrastructure.RequestConfig
import com.currencycore.sdk.infrastructure.RequestMethod
import com.currencycore.sdk.infrastructure.ResponseType
import com.currencycore.sdk.infrastructure.Success
import com.currencycore.sdk.infrastructure.toMultiValue

open class CurrencyCoreApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.currency-core.com/v1")
        }
    }

    /**
     * GET /ai
     * AI
     * Ask a natural-language currency question; the model answers using live rates.
     * @param q A natural-language question, e.g. \&quot;Convert 50 euro to indian rupees\&quot; or \&quot;What&#39;s the USD to EUR rate today?\&quot;.
     * @return AiResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ai(q: kotlin.String) : AiResponse {
        val localVarResponse = aiWithHttpInfo(q = q)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AiResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /ai
     * AI
     * Ask a natural-language currency question; the model answers using live rates.
     * @param q A natural-language question, e.g. \&quot;Convert 50 euro to indian rupees\&quot; or \&quot;What&#39;s the USD to EUR rate today?\&quot;.
     * @return ApiResponse<AiResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun aiWithHttpInfo(q: kotlin.String) : ApiResponse<AiResponse?> {
        val localVariableConfig = aiRequestConfig(q = q)

        return request<Unit, AiResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ai
     *
     * @param q A natural-language question, e.g. \&quot;Convert 50 euro to indian rupees\&quot; or \&quot;What&#39;s the USD to EUR rate today?\&quot;.
     * @return RequestConfig
     */
    fun aiRequestConfig(q: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("q", listOf(q.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/ai",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /convert
     * Convert
     * Convert an amount between currencies, optionally PPP-adjusted.
     * @param from Source currency (ISO 4217), e.g. USD. For PPP (ppp&#x3D;true) pair it with a country as CUR:COUNTRY, e.g. USD:USA.
     * @param to One or more target currencies, comma-separated, e.g. EUR,INR (max 25). For PPP use CUR:COUNTRY pairs, e.g. EUR:DEU,INR:IND.
     * @param amount Amount to convert. Optional, defaults to 1 (so each result equals the rate). (optional)
     * @param ppp When true, apply a PPP adjustment. Every currency must then carry a country code. (optional)
     * @param date Rate date in YYYY-MM-DD (UTC). Must not be in the future. Defaults to latest. (optional)
     * @return ConvertResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun convert(from: kotlin.String, to: kotlin.String, amount: java.math.BigDecimal? = null, ppp: kotlin.Boolean? = null, date: kotlin.String? = null) : ConvertResponse {
        val localVarResponse = convertWithHttpInfo(from = from, to = to, amount = amount, ppp = ppp, date = date)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConvertResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /convert
     * Convert
     * Convert an amount between currencies, optionally PPP-adjusted.
     * @param from Source currency (ISO 4217), e.g. USD. For PPP (ppp&#x3D;true) pair it with a country as CUR:COUNTRY, e.g. USD:USA.
     * @param to One or more target currencies, comma-separated, e.g. EUR,INR (max 25). For PPP use CUR:COUNTRY pairs, e.g. EUR:DEU,INR:IND.
     * @param amount Amount to convert. Optional, defaults to 1 (so each result equals the rate). (optional)
     * @param ppp When true, apply a PPP adjustment. Every currency must then carry a country code. (optional)
     * @param date Rate date in YYYY-MM-DD (UTC). Must not be in the future. Defaults to latest. (optional)
     * @return ApiResponse<ConvertResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun convertWithHttpInfo(from: kotlin.String, to: kotlin.String, amount: java.math.BigDecimal?, ppp: kotlin.Boolean?, date: kotlin.String?) : ApiResponse<ConvertResponse?> {
        val localVariableConfig = convertRequestConfig(from = from, to = to, amount = amount, ppp = ppp, date = date)

        return request<Unit, ConvertResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation convert
     *
     * @param from Source currency (ISO 4217), e.g. USD. For PPP (ppp&#x3D;true) pair it with a country as CUR:COUNTRY, e.g. USD:USA.
     * @param to One or more target currencies, comma-separated, e.g. EUR,INR (max 25). For PPP use CUR:COUNTRY pairs, e.g. EUR:DEU,INR:IND.
     * @param amount Amount to convert. Optional, defaults to 1 (so each result equals the rate). (optional)
     * @param ppp When true, apply a PPP adjustment. Every currency must then carry a country code. (optional)
     * @param date Rate date in YYYY-MM-DD (UTC). Must not be in the future. Defaults to latest. (optional)
     * @return RequestConfig
     */
    fun convertRequestConfig(from: kotlin.String, to: kotlin.String, amount: java.math.BigDecimal?, ppp: kotlin.Boolean?, date: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("from", listOf(from.toString()))
                put("to", listOf(to.toString()))
                if (amount != null) {
                    put("amount", listOf(amount.toString()))
                }
                if (ppp != null) {
                    put("ppp", listOf(ppp.toString()))
                }
                if (date != null) {
                    put("date", listOf(date.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/convert",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /correlation
     * Correlation
     * Correlation of each currency&#39;s daily returns with a base currency&#39;s, over a window. Growth plan or higher.
     * @param currencies Comma-separated currencies to correlate with &#x60;base&#x60;, e.g. GBP,CHF,SEK.
     * @param base Reference currency to correlate against (3-letter ISO 4217). Defaults to USD (a non-USD base is more meaningful). (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @return CorrelationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun correlation(currencies: kotlin.String, base: kotlin.String? = null, from: kotlin.String? = null, to: kotlin.String? = null) : CorrelationResponse {
        val localVarResponse = correlationWithHttpInfo(currencies = currencies, base = base, from = from, to = to)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CorrelationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /correlation
     * Correlation
     * Correlation of each currency&#39;s daily returns with a base currency&#39;s, over a window. Growth plan or higher.
     * @param currencies Comma-separated currencies to correlate with &#x60;base&#x60;, e.g. GBP,CHF,SEK.
     * @param base Reference currency to correlate against (3-letter ISO 4217). Defaults to USD (a non-USD base is more meaningful). (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @return ApiResponse<CorrelationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun correlationWithHttpInfo(currencies: kotlin.String, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?) : ApiResponse<CorrelationResponse?> {
        val localVariableConfig = correlationRequestConfig(currencies = currencies, base = base, from = from, to = to)

        return request<Unit, CorrelationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation correlation
     *
     * @param currencies Comma-separated currencies to correlate with &#x60;base&#x60;, e.g. GBP,CHF,SEK.
     * @param base Reference currency to correlate against (3-letter ISO 4217). Defaults to USD (a non-USD base is more meaningful). (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @return RequestConfig
     */
    fun correlationRequestConfig(currencies: kotlin.String, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (base != null) {
                    put("base", listOf(base.toString()))
                }
                put("currencies", listOf(currencies.toString()))
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/correlation",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /countries
     * Countries
     * The supported countries and their official currencies. Public, no key needed.
     * @return kotlin.collections.List<CountriesResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun countries() : kotlin.collections.List<CountriesResponseInner> {
        val localVarResponse = countriesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CountriesResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /countries
     * Countries
     * The supported countries and their official currencies. Public, no key needed.
     * @return ApiResponse<kotlin.collections.List<CountriesResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun countriesWithHttpInfo() : ApiResponse<kotlin.collections.List<CountriesResponseInner>?> {
        val localVariableConfig = countriesRequestConfig()

        return request<Unit, kotlin.collections.List<CountriesResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation countries
     *
     * @return RequestConfig
     */
    fun countriesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/countries",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /currencies
     * Currencies
     * The full list of supported ISO 4217 currencies. Use it to resolve a name or symbol to its code, or to check whether a currency is supported (so a missing one fails clearly, not silently). Public, no key needed.
     * @return kotlin.collections.List<CurrenciesResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun currencies() : kotlin.collections.List<CurrenciesResponseInner> {
        val localVarResponse = currenciesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CurrenciesResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /currencies
     * Currencies
     * The full list of supported ISO 4217 currencies. Use it to resolve a name or symbol to its code, or to check whether a currency is supported (so a missing one fails clearly, not silently). Public, no key needed.
     * @return ApiResponse<kotlin.collections.List<CurrenciesResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun currenciesWithHttpInfo() : ApiResponse<kotlin.collections.List<CurrenciesResponseInner>?> {
        val localVariableConfig = currenciesRequestConfig()

        return request<Unit, kotlin.collections.List<CurrenciesResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation currencies
     *
     * @return RequestConfig
     */
    fun currenciesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/currencies",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /drawdown
     * Drawdown
     * Maximum peak-to-trough decline vs a base (with peak/trough/recovery), or a drawdown ranking. Growth plan or higher.
     * @param currency Currency to measure (3-letter ISO 4217), or a comma-separated list. OMIT to RANK the liquid set by drawdown. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param sort Ranking direction: deepest (largest decline first, default) or recovery (fastest recovery first). (optional)
     * @param universe Ranking universe: liquid (default) or majors. (optional)
     * @param limit Ranking: how many to return (default 10, max 50). (optional)
     * @return DrawdownResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun drawdown(currency: kotlin.String? = null, base: kotlin.String? = null, from: kotlin.String? = null, to: kotlin.String? = null, sort: kotlin.String? = null, universe: kotlin.String? = null, limit: java.math.BigDecimal? = null) : DrawdownResponse {
        val localVarResponse = drawdownWithHttpInfo(currency = currency, base = base, from = from, to = to, sort = sort, universe = universe, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DrawdownResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /drawdown
     * Drawdown
     * Maximum peak-to-trough decline vs a base (with peak/trough/recovery), or a drawdown ranking. Growth plan or higher.
     * @param currency Currency to measure (3-letter ISO 4217), or a comma-separated list. OMIT to RANK the liquid set by drawdown. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param sort Ranking direction: deepest (largest decline first, default) or recovery (fastest recovery first). (optional)
     * @param universe Ranking universe: liquid (default) or majors. (optional)
     * @param limit Ranking: how many to return (default 10, max 50). (optional)
     * @return ApiResponse<DrawdownResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun drawdownWithHttpInfo(currency: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, sort: kotlin.String?, universe: kotlin.String?, limit: java.math.BigDecimal?) : ApiResponse<DrawdownResponse?> {
        val localVariableConfig = drawdownRequestConfig(currency = currency, base = base, from = from, to = to, sort = sort, universe = universe, limit = limit)

        return request<Unit, DrawdownResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation drawdown
     *
     * @param currency Currency to measure (3-letter ISO 4217), or a comma-separated list. OMIT to RANK the liquid set by drawdown. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param sort Ranking direction: deepest (largest decline first, default) or recovery (fastest recovery first). (optional)
     * @param universe Ranking universe: liquid (default) or majors. (optional)
     * @param limit Ranking: how many to return (default 10, max 50). (optional)
     * @return RequestConfig
     */
    fun drawdownRequestConfig(currency: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, sort: kotlin.String?, universe: kotlin.String?, limit: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (currency != null) {
                    put("currency", listOf(currency.toString()))
                }
                if (base != null) {
                    put("base", listOf(base.toString()))
                }
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (universe != null) {
                    put("universe", listOf(universe.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/drawdown",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /history
     * History
     * A single currency&#39;s daily rate time series over a date range. Growth plan or higher.
     * @param currency The currency whose history to fetch (3-letter ISO 4217), e.g. INR. One currency per call.
     * @param from Start date YYYY-MM-DD (UTC). Defaults to 7 days before &#x60;to&#x60;. (optional)
     * @param to End date YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param base Base currency the rates are expressed against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param interval Aggregation: daily (default), weekly, monthly, or yearly. Coarser intervals average the daily rates per bucket (weekly key &#x3D; the week&#39;s Monday, monthly &#x3D; YYYY-MM, yearly &#x3D; YYYY). (optional)
     * @return HistoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun history(currency: kotlin.String, from: kotlin.String? = null, to: kotlin.String? = null, base: kotlin.String? = null, interval: kotlin.String? = null) : HistoryResponse {
        val localVarResponse = historyWithHttpInfo(currency = currency, from = from, to = to, base = base, interval = interval)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HistoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /history
     * History
     * A single currency&#39;s daily rate time series over a date range. Growth plan or higher.
     * @param currency The currency whose history to fetch (3-letter ISO 4217), e.g. INR. One currency per call.
     * @param from Start date YYYY-MM-DD (UTC). Defaults to 7 days before &#x60;to&#x60;. (optional)
     * @param to End date YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param base Base currency the rates are expressed against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param interval Aggregation: daily (default), weekly, monthly, or yearly. Coarser intervals average the daily rates per bucket (weekly key &#x3D; the week&#39;s Monday, monthly &#x3D; YYYY-MM, yearly &#x3D; YYYY). (optional)
     * @return ApiResponse<HistoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun historyWithHttpInfo(currency: kotlin.String, from: kotlin.String?, to: kotlin.String?, base: kotlin.String?, interval: kotlin.String?) : ApiResponse<HistoryResponse?> {
        val localVariableConfig = historyRequestConfig(currency = currency, from = from, to = to, base = base, interval = interval)

        return request<Unit, HistoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation history
     *
     * @param currency The currency whose history to fetch (3-letter ISO 4217), e.g. INR. One currency per call.
     * @param from Start date YYYY-MM-DD (UTC). Defaults to 7 days before &#x60;to&#x60;. (optional)
     * @param to End date YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param base Base currency the rates are expressed against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param interval Aggregation: daily (default), weekly, monthly, or yearly. Coarser intervals average the daily rates per bucket (weekly key &#x3D; the week&#39;s Monday, monthly &#x3D; YYYY-MM, yearly &#x3D; YYYY). (optional)
     * @return RequestConfig
     */
    fun historyRequestConfig(currency: kotlin.String, from: kotlin.String?, to: kotlin.String?, base: kotlin.String?, interval: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("currency", listOf(currency.toString()))
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
                if (base != null) {
                    put("base", listOf(base.toString()))
                }
                if (interval != null) {
                    put("interval", listOf(interval.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/history",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /history/analysis
     * History analysis
     * Trends, comparisons &amp; &#39;movers&#39;: % change, strength, and min/max/avg over a window. Growth plan or higher.
     * @param base Currency everything is measured against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param currencies Comma-separated currencies to compare, e.g. GBP,EUR,AED. OMIT to rank ALL currencies vs base (&#39;movers&#39; mode). (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 20 years (2 decades) before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param period Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 6m, 30d, ytd, max. Ignored if &#x60;from&#x60; is given. (optional)
     * @param sort Movers ranking: strengthened (default) or weakened. (optional)
     * @param assetClass Movers universe: fiat (default, the liquid tradeable currencies), metals (XAU/XAG/XPT/XPD), or all (every currency incl. illiquid/frontier). fiat excludes metals/synthetics + illiquid frontier codes; redenomination artifacts are always dropped. (optional)
     * @param limit Movers: how many top results to return (default 10, max 200). (optional)
     * @param interval Attach a trend series per named currency: weekly, monthly, or yearly (compare mode only). (optional)
     * @param stats Include min/max/avg over the window per currency. Defaults to true; pass false to skip. (optional)
     * @return HistoryAnalysisResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun historyAnalysis(base: kotlin.String? = null, currencies: kotlin.String? = null, from: kotlin.String? = null, to: kotlin.String? = null, period: kotlin.String? = null, sort: kotlin.String? = null, assetClass: kotlin.String? = null, limit: java.math.BigDecimal? = null, interval: kotlin.String? = null, stats: kotlin.Boolean? = null) : HistoryAnalysisResponse {
        val localVarResponse = historyAnalysisWithHttpInfo(base = base, currencies = currencies, from = from, to = to, period = period, sort = sort, assetClass = assetClass, limit = limit, interval = interval, stats = stats)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HistoryAnalysisResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /history/analysis
     * History analysis
     * Trends, comparisons &amp; &#39;movers&#39;: % change, strength, and min/max/avg over a window. Growth plan or higher.
     * @param base Currency everything is measured against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param currencies Comma-separated currencies to compare, e.g. GBP,EUR,AED. OMIT to rank ALL currencies vs base (&#39;movers&#39; mode). (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 20 years (2 decades) before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param period Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 6m, 30d, ytd, max. Ignored if &#x60;from&#x60; is given. (optional)
     * @param sort Movers ranking: strengthened (default) or weakened. (optional)
     * @param assetClass Movers universe: fiat (default, the liquid tradeable currencies), metals (XAU/XAG/XPT/XPD), or all (every currency incl. illiquid/frontier). fiat excludes metals/synthetics + illiquid frontier codes; redenomination artifacts are always dropped. (optional)
     * @param limit Movers: how many top results to return (default 10, max 200). (optional)
     * @param interval Attach a trend series per named currency: weekly, monthly, or yearly (compare mode only). (optional)
     * @param stats Include min/max/avg over the window per currency. Defaults to true; pass false to skip. (optional)
     * @return ApiResponse<HistoryAnalysisResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun historyAnalysisWithHttpInfo(base: kotlin.String?, currencies: kotlin.String?, from: kotlin.String?, to: kotlin.String?, period: kotlin.String?, sort: kotlin.String?, assetClass: kotlin.String?, limit: java.math.BigDecimal?, interval: kotlin.String?, stats: kotlin.Boolean?) : ApiResponse<HistoryAnalysisResponse?> {
        val localVariableConfig = historyAnalysisRequestConfig(base = base, currencies = currencies, from = from, to = to, period = period, sort = sort, assetClass = assetClass, limit = limit, interval = interval, stats = stats)

        return request<Unit, HistoryAnalysisResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation historyAnalysis
     *
     * @param base Currency everything is measured against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param currencies Comma-separated currencies to compare, e.g. GBP,EUR,AED. OMIT to rank ALL currencies vs base (&#39;movers&#39; mode). (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 20 years (2 decades) before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param period Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 6m, 30d, ytd, max. Ignored if &#x60;from&#x60; is given. (optional)
     * @param sort Movers ranking: strengthened (default) or weakened. (optional)
     * @param assetClass Movers universe: fiat (default, the liquid tradeable currencies), metals (XAU/XAG/XPT/XPD), or all (every currency incl. illiquid/frontier). fiat excludes metals/synthetics + illiquid frontier codes; redenomination artifacts are always dropped. (optional)
     * @param limit Movers: how many top results to return (default 10, max 200). (optional)
     * @param interval Attach a trend series per named currency: weekly, monthly, or yearly (compare mode only). (optional)
     * @param stats Include min/max/avg over the window per currency. Defaults to true; pass false to skip. (optional)
     * @return RequestConfig
     */
    fun historyAnalysisRequestConfig(base: kotlin.String?, currencies: kotlin.String?, from: kotlin.String?, to: kotlin.String?, period: kotlin.String?, sort: kotlin.String?, assetClass: kotlin.String?, limit: java.math.BigDecimal?, interval: kotlin.String?, stats: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (base != null) {
                    put("base", listOf(base.toString()))
                }
                if (currencies != null) {
                    put("currencies", listOf(currencies.toString()))
                }
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
                if (period != null) {
                    put("period", listOf(period.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (assetClass != null) {
                    put("assetClass", listOf(assetClass.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (interval != null) {
                    put("interval", listOf(interval.toString()))
                }
                if (stats != null) {
                    put("stats", listOf(stats.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/history/analysis",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /mean-reversion
     * Mean reversion
     * Ranks currencies by how strongly they revert to their mean (crossing frequency + reversion half-life). Growth plan or higher.
     * @param currencies Comma-separated currencies to score, e.g. EUR,GBP. OMIT to rank the liquid set. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to ~2 years before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param limit How many to return (default 10, max 50). (optional)
     * @return MeanReversionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun meanReversion(currencies: kotlin.String? = null, base: kotlin.String? = null, from: kotlin.String? = null, to: kotlin.String? = null, limit: java.math.BigDecimal? = null) : MeanReversionResponse {
        val localVarResponse = meanReversionWithHttpInfo(currencies = currencies, base = base, from = from, to = to, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MeanReversionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /mean-reversion
     * Mean reversion
     * Ranks currencies by how strongly they revert to their mean (crossing frequency + reversion half-life). Growth plan or higher.
     * @param currencies Comma-separated currencies to score, e.g. EUR,GBP. OMIT to rank the liquid set. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to ~2 years before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param limit How many to return (default 10, max 50). (optional)
     * @return ApiResponse<MeanReversionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun meanReversionWithHttpInfo(currencies: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, limit: java.math.BigDecimal?) : ApiResponse<MeanReversionResponse?> {
        val localVariableConfig = meanReversionRequestConfig(currencies = currencies, base = base, from = from, to = to, limit = limit)

        return request<Unit, MeanReversionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation meanReversion
     *
     * @param currencies Comma-separated currencies to score, e.g. EUR,GBP. OMIT to rank the liquid set. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to ~2 years before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param limit How many to return (default 10, max 50). (optional)
     * @return RequestConfig
     */
    fun meanReversionRequestConfig(currencies: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, limit: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (currencies != null) {
                    put("currencies", listOf(currencies.toString()))
                }
                if (base != null) {
                    put("base", listOf(base.toString()))
                }
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/mean-reversion",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /ppp/analysis
     * PPP analysis
     * PPP over time: how a country&#39;s purchasing-power-parity factor changed, comparing countries, or &#39;movers&#39;. Growth plan or higher.
     * @param countries Comma-separated ISO 3166-1 alpha-3 country codes to compare, e.g. IND,DEU,USA. OMIT to rank ALL countries by PPP-factor change (&#39;movers&#39; mode). (optional)
     * @param from Window start YEAR (e.g. 2015). Defaults to 10 years before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     * @param to Window end YEAR (e.g. 2024). Defaults to the current year. (optional)
     * @param period Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 20y, max. Ignored if &#x60;from&#x60; is given. (optional)
     * @param sort Movers ranking: increased (PPP factor rose most, default) or decreased. (optional)
     * @param limit Movers: how many top results to return (default 10, max 200). (optional)
     * @param stats Include min/max/avg of the PPP factor over the window per country. Defaults to true; pass false to skip. (optional)
     * @return PppAnalysisResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun pppAnalysis(countries: kotlin.String? = null, from: kotlin.String? = null, to: kotlin.String? = null, period: kotlin.String? = null, sort: kotlin.String? = null, limit: java.math.BigDecimal? = null, stats: kotlin.Boolean? = null) : PppAnalysisResponse {
        val localVarResponse = pppAnalysisWithHttpInfo(countries = countries, from = from, to = to, period = period, sort = sort, limit = limit, stats = stats)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PppAnalysisResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /ppp/analysis
     * PPP analysis
     * PPP over time: how a country&#39;s purchasing-power-parity factor changed, comparing countries, or &#39;movers&#39;. Growth plan or higher.
     * @param countries Comma-separated ISO 3166-1 alpha-3 country codes to compare, e.g. IND,DEU,USA. OMIT to rank ALL countries by PPP-factor change (&#39;movers&#39; mode). (optional)
     * @param from Window start YEAR (e.g. 2015). Defaults to 10 years before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     * @param to Window end YEAR (e.g. 2024). Defaults to the current year. (optional)
     * @param period Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 20y, max. Ignored if &#x60;from&#x60; is given. (optional)
     * @param sort Movers ranking: increased (PPP factor rose most, default) or decreased. (optional)
     * @param limit Movers: how many top results to return (default 10, max 200). (optional)
     * @param stats Include min/max/avg of the PPP factor over the window per country. Defaults to true; pass false to skip. (optional)
     * @return ApiResponse<PppAnalysisResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun pppAnalysisWithHttpInfo(countries: kotlin.String?, from: kotlin.String?, to: kotlin.String?, period: kotlin.String?, sort: kotlin.String?, limit: java.math.BigDecimal?, stats: kotlin.Boolean?) : ApiResponse<PppAnalysisResponse?> {
        val localVariableConfig = pppAnalysisRequestConfig(countries = countries, from = from, to = to, period = period, sort = sort, limit = limit, stats = stats)

        return request<Unit, PppAnalysisResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pppAnalysis
     *
     * @param countries Comma-separated ISO 3166-1 alpha-3 country codes to compare, e.g. IND,DEU,USA. OMIT to rank ALL countries by PPP-factor change (&#39;movers&#39; mode). (optional)
     * @param from Window start YEAR (e.g. 2015). Defaults to 10 years before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     * @param to Window end YEAR (e.g. 2024). Defaults to the current year. (optional)
     * @param period Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 20y, max. Ignored if &#x60;from&#x60; is given. (optional)
     * @param sort Movers ranking: increased (PPP factor rose most, default) or decreased. (optional)
     * @param limit Movers: how many top results to return (default 10, max 200). (optional)
     * @param stats Include min/max/avg of the PPP factor over the window per country. Defaults to true; pass false to skip. (optional)
     * @return RequestConfig
     */
    fun pppAnalysisRequestConfig(countries: kotlin.String?, from: kotlin.String?, to: kotlin.String?, period: kotlin.String?, sort: kotlin.String?, limit: java.math.BigDecimal?, stats: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (countries != null) {
                    put("countries", listOf(countries.toString()))
                }
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
                if (period != null) {
                    put("period", listOf(period.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (stats != null) {
                    put("stats", listOf(stats.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/ppp/analysis",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /rates
     * Rates
     * The full exchange-rate snapshot for a date (USD base).
     * @param date YYYY-MM-DD. Defaults to the latest available date. (optional)
     * @return RatesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun rates(date: kotlin.String? = null) : RatesResponse {
        val localVarResponse = ratesWithHttpInfo(date = date)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RatesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /rates
     * Rates
     * The full exchange-rate snapshot for a date (USD base).
     * @param date YYYY-MM-DD. Defaults to the latest available date. (optional)
     * @return ApiResponse<RatesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ratesWithHttpInfo(date: kotlin.String?) : ApiResponse<RatesResponse?> {
        val localVariableConfig = ratesRequestConfig(date = date)

        return request<Unit, RatesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation rates
     *
     * @param date YYYY-MM-DD. Defaults to the latest available date. (optional)
     * @return RequestConfig
     */
    fun ratesRequestConfig(date: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (date != null) {
                    put("date", listOf(date.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/rates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /rates/{base}
     * Rates by base
     * The same snapshot re-expressed against any base currency.
     * @param base Base currency (3-letter ISO 4217), e.g. EUR.
     * @param date YYYY-MM-DD. Defaults to the latest available date. (optional)
     * @return RatesByBaseResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ratesByBase(base: kotlin.String, date: kotlin.String? = null) : RatesByBaseResponse {
        val localVarResponse = ratesByBaseWithHttpInfo(base = base, date = date)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RatesByBaseResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /rates/{base}
     * Rates by base
     * The same snapshot re-expressed against any base currency.
     * @param base Base currency (3-letter ISO 4217), e.g. EUR.
     * @param date YYYY-MM-DD. Defaults to the latest available date. (optional)
     * @return ApiResponse<RatesByBaseResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ratesByBaseWithHttpInfo(base: kotlin.String, date: kotlin.String?) : ApiResponse<RatesByBaseResponse?> {
        val localVariableConfig = ratesByBaseRequestConfig(base = base, date = date)

        return request<Unit, RatesByBaseResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ratesByBase
     *
     * @param base Base currency (3-letter ISO 4217), e.g. EUR.
     * @param date YYYY-MM-DD. Defaults to the latest available date. (optional)
     * @return RequestConfig
     */
    fun ratesByBaseRequestConfig(base: kotlin.String, date: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (date != null) {
                    put("date", listOf(date.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/rates/{base}".replace("{"+"base"+"}", encodeURIComponent(base.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /safe-haven
     * Safe haven
     * Ranks currencies by a composite safe-haven score (low volatility + shallow drawdown + 2008-crisis resilience). Growth plan or higher.
     * @param currencies Comma-separated currencies to score, e.g. CHF,JPY. OMIT to rank the safe-haven pool (includes gold). (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 2007-01-01 (spans the 2008 crisis + COVID). (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param limit How many to return (default 10, max 50). (optional)
     * @return SafeHavenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun safeHaven(currencies: kotlin.String? = null, base: kotlin.String? = null, from: kotlin.String? = null, to: kotlin.String? = null, limit: java.math.BigDecimal? = null) : SafeHavenResponse {
        val localVarResponse = safeHavenWithHttpInfo(currencies = currencies, base = base, from = from, to = to, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SafeHavenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /safe-haven
     * Safe haven
     * Ranks currencies by a composite safe-haven score (low volatility + shallow drawdown + 2008-crisis resilience). Growth plan or higher.
     * @param currencies Comma-separated currencies to score, e.g. CHF,JPY. OMIT to rank the safe-haven pool (includes gold). (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 2007-01-01 (spans the 2008 crisis + COVID). (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param limit How many to return (default 10, max 50). (optional)
     * @return ApiResponse<SafeHavenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun safeHavenWithHttpInfo(currencies: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, limit: java.math.BigDecimal?) : ApiResponse<SafeHavenResponse?> {
        val localVariableConfig = safeHavenRequestConfig(currencies = currencies, base = base, from = from, to = to, limit = limit)

        return request<Unit, SafeHavenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation safeHaven
     *
     * @param currencies Comma-separated currencies to score, e.g. CHF,JPY. OMIT to rank the safe-haven pool (includes gold). (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 2007-01-01 (spans the 2008 crisis + COVID). (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     * @param limit How many to return (default 10, max 50). (optional)
     * @return RequestConfig
     */
    fun safeHavenRequestConfig(currencies: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, limit: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (currencies != null) {
                    put("currencies", listOf(currencies.toString()))
                }
                if (base != null) {
                    put("base", listOf(base.toString()))
                }
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/safe-haven",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /volatility
     * Volatility
     * Annualized volatility of a currency vs a base, or a stability ranking of the liquid currencies. Growth plan or higher.
     * @param currency Currency to measure (3-letter ISO 4217), or a comma-separated list to compare. OMIT to RANK the liquid-currency set by stability. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param sort Ranking direction: stable (least volatile first, default) or volatile. (optional)
     * @param universe Ranking universe: liquid (default, broad set) or majors (USD/EUR/GBP/JPY/CHF/CAD/AUD/NZD). Use majors for &#39;most volatile major pair&#39;. (optional)
     * @param limit Ranking: how many to return (default 10, max 50). (optional)
     * @return VolatilityResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun volatility(currency: kotlin.String? = null, base: kotlin.String? = null, from: kotlin.String? = null, to: kotlin.String? = null, sort: kotlin.String? = null, universe: kotlin.String? = null, limit: java.math.BigDecimal? = null) : VolatilityResponse {
        val localVarResponse = volatilityWithHttpInfo(currency = currency, base = base, from = from, to = to, sort = sort, universe = universe, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as VolatilityResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /volatility
     * Volatility
     * Annualized volatility of a currency vs a base, or a stability ranking of the liquid currencies. Growth plan or higher.
     * @param currency Currency to measure (3-letter ISO 4217), or a comma-separated list to compare. OMIT to RANK the liquid-currency set by stability. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param sort Ranking direction: stable (least volatile first, default) or volatile. (optional)
     * @param universe Ranking universe: liquid (default, broad set) or majors (USD/EUR/GBP/JPY/CHF/CAD/AUD/NZD). Use majors for &#39;most volatile major pair&#39;. (optional)
     * @param limit Ranking: how many to return (default 10, max 50). (optional)
     * @return ApiResponse<VolatilityResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun volatilityWithHttpInfo(currency: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, sort: kotlin.String?, universe: kotlin.String?, limit: java.math.BigDecimal?) : ApiResponse<VolatilityResponse?> {
        val localVariableConfig = volatilityRequestConfig(currency = currency, base = base, from = from, to = to, sort = sort, universe = universe, limit = limit)

        return request<Unit, VolatilityResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation volatility
     *
     * @param currency Currency to measure (3-letter ISO 4217), or a comma-separated list to compare. OMIT to RANK the liquid-currency set by stability. (optional)
     * @param base Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     * @param from Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     * @param to Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     * @param sort Ranking direction: stable (least volatile first, default) or volatile. (optional)
     * @param universe Ranking universe: liquid (default, broad set) or majors (USD/EUR/GBP/JPY/CHF/CAD/AUD/NZD). Use majors for &#39;most volatile major pair&#39;. (optional)
     * @param limit Ranking: how many to return (default 10, max 50). (optional)
     * @return RequestConfig
     */
    fun volatilityRequestConfig(currency: kotlin.String?, base: kotlin.String?, from: kotlin.String?, to: kotlin.String?, sort: kotlin.String?, universe: kotlin.String?, limit: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (currency != null) {
                    put("currency", listOf(currency.toString()))
                }
                if (base != null) {
                    put("base", listOf(base.toString()))
                }
                if (from != null) {
                    put("from", listOf(from.toString()))
                }
                if (to != null) {
                    put("to", listOf(to.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (universe != null) {
                    put("universe", listOf(universe.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/volatility",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
