/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param query 
 * @param answer 
 * @param `data` 
 * @param toolCalls 
 */


data class AiResponse (

    @Json(name = "query")
    val query: kotlin.String,

    @Json(name = "answer")
    val answer: kotlin.String,

    @Json(name = "data")
    val `data`: kotlin.collections.List<kotlin.Any?>,

    @Json(name = "toolCalls")
    val toolCalls: java.math.BigDecimal? = null

) {


}

