/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.ConvertResponseResultsInnerPpp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param to 
 * @param result 
 * @param rate 
 * @param toCountry 
 * @param ppp 
 */


data class ConvertResponseResultsInner (

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "result")
    val result: java.math.BigDecimal,

    @Json(name = "rate")
    val rate: java.math.BigDecimal,

    @Json(name = "toCountry")
    val toCountry: kotlin.String? = null,

    @Json(name = "ppp")
    val ppp: ConvertResponseResultsInnerPpp? = null

) {


}

