/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.ConvertResponseResultsInnerPppAnyOf
import com.currencycore.sdk.models.ConvertResponseResultsInnerPppAnyOf1

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fromFactor 
 * @param toFactor 
 * @param result 
 * @param year 
 * @param source 
 * @param error 
 */


data class ConvertResponseResultsInnerPpp (

    @Json(name = "fromFactor")
    val fromFactor: java.math.BigDecimal,

    @Json(name = "toFactor")
    val toFactor: java.math.BigDecimal,

    @Json(name = "result")
    val result: java.math.BigDecimal,

    @Json(name = "year")
    val year: java.math.BigDecimal,

    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "error")
    val error: kotlin.String

) {


}

