/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.ConvertResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param from 
 * @param amount 
 * @param date 
 * @param results 
 * @param fromCountry 
 * @param requestedDate 
 * @param asOf 
 * @param message 
 */


data class ConvertResponse (

    @Json(name = "from")
    val from: kotlin.String,

    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    @Json(name = "date")
    val date: kotlin.String,

    @Json(name = "results")
    val results: kotlin.collections.List<ConvertResponseResultsInner>,

    @Json(name = "fromCountry")
    val fromCountry: kotlin.String? = null,

    @Json(name = "requestedDate")
    val requestedDate: kotlin.String? = null,

    @Json(name = "asOf")
    val asOf: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "message")
    val message: kotlin.String? = null

) {


}

