/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param correlation 
 * @param observations 
 * @param note 
 */


data class CorrelationResponseResultsInner (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "correlation")
    val correlation: java.math.BigDecimal?,

    @Json(name = "observations")
    val observations: java.math.BigDecimal,

    @Json(name = "note")
    val note: kotlin.String? = null

) {


}

