/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param numeric 
 * @param name 
 * @param symbol 
 */


data class CurrenciesResponseInner (

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "numeric")
    val numeric: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "symbol")
    val symbol: kotlin.String

) {


}

