/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param maxDrawdownPct 
 * @param peakDate 
 * @param troughDate 
 * @param recoveryDate 
 * @param recoveryDays 
 * @param note 
 */


data class DrawdownResponseResultsInner (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "maxDrawdownPct")
    val maxDrawdownPct: java.math.BigDecimal?,

    @Json(name = "peakDate")
    val peakDate: kotlin.String? = null,

    @Json(name = "troughDate")
    val troughDate: kotlin.String? = null,

    @Json(name = "recoveryDate")
    val recoveryDate: kotlin.String? = null,

    @Json(name = "recoveryDays")
    val recoveryDays: java.math.BigDecimal? = null,

    @Json(name = "note")
    val note: kotlin.String? = null

) {


}

