/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param base 
 * @param interval 
 * @param from 
 * @param to 
 * @param rates 
 */


data class HistoryResponse (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "base")
    val base: kotlin.String,

    @Json(name = "interval")
    val interval: HistoryResponse.Interval,

    @Json(name = "from")
    val from: kotlin.String,

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "rates")
    val rates: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>

) {

    /**
     * 
     *
     * Values: daily,weekly,monthly,yearly
     */
    @JsonClass(generateAdapter = false)
    enum class Interval(val value: kotlin.String) {
        @Json(name = "daily") daily("daily"),
        @Json(name = "weekly") weekly("weekly"),
        @Json(name = "monthly") monthly("monthly"),
        @Json(name = "yearly") yearly("yearly");
    }

}

