/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.HistoryAnalysisResponseResultsInnerStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param startDate 
 * @param endDate 
 * @param startRate 
 * @param endRate 
 * @param changePct 
 * @param strengthenedPct 
 * @param stats 
 * @param series 
 * @param volatility 
 * @param note 
 */


data class HistoryAnalysisResponseResultsInner (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "startDate")
    val startDate: kotlin.String,

    @Json(name = "endDate")
    val endDate: kotlin.String,

    @Json(name = "startRate")
    val startRate: java.math.BigDecimal?,

    @Json(name = "endRate")
    val endRate: java.math.BigDecimal?,

    @Json(name = "changePct")
    val changePct: java.math.BigDecimal?,

    @Json(name = "strengthenedPct")
    val strengthenedPct: java.math.BigDecimal?,

    @Json(name = "stats")
    val stats: HistoryAnalysisResponseResultsInnerStats? = null,

    @Json(name = "series")
    val series: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null,

    @Json(name = "volatility")
    val volatility: java.math.BigDecimal? = null,

    @Json(name = "note")
    val note: kotlin.String? = null

) {


}

