/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.HistoryAnalysisResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param base 
 * @param from 
 * @param to 
 * @param mode 
 * @param stats 
 * @param results 
 * @param sort 
 * @param assetClass 
 * @param interval 
 */


data class HistoryAnalysisResponse (

    @Json(name = "base")
    val base: kotlin.String,

    @Json(name = "from")
    val from: kotlin.String,

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "mode")
    val mode: HistoryAnalysisResponse.Mode,

    @Json(name = "stats")
    val stats: kotlin.Boolean,

    @Json(name = "results")
    val results: kotlin.collections.List<HistoryAnalysisResponseResultsInner>,

    @Json(name = "sort")
    val sort: HistoryAnalysisResponse.Sort? = null,

    @Json(name = "assetClass")
    val assetClass: HistoryAnalysisResponse.AssetClass? = null,

    @Json(name = "interval")
    val interval: HistoryAnalysisResponse.Interval? = null

) {

    /**
     * 
     *
     * Values: compare,movers
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "compare") compare("compare"),
        @Json(name = "movers") movers("movers");
    }
    /**
     * 
     *
     * Values: strengthened,weakened
     */
    @JsonClass(generateAdapter = false)
    enum class Sort(val value: kotlin.String) {
        @Json(name = "strengthened") strengthened("strengthened"),
        @Json(name = "weakened") weakened("weakened");
    }
    /**
     * 
     *
     * Values: fiat,metals,all,crypto
     */
    @JsonClass(generateAdapter = false)
    enum class AssetClass(val value: kotlin.String) {
        @Json(name = "fiat") fiat("fiat"),
        @Json(name = "metals") metals("metals"),
        @Json(name = "all") all("all"),
        @Json(name = "crypto") crypto("crypto");
    }
    /**
     * 
     *
     * Values: daily,weekly,monthly,yearly
     */
    @JsonClass(generateAdapter = false)
    enum class Interval(val value: kotlin.String) {
        @Json(name = "daily") daily("daily"),
        @Json(name = "weekly") weekly("weekly"),
        @Json(name = "monthly") monthly("monthly"),
        @Json(name = "yearly") yearly("yearly");
    }

}

