/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.MeanReversionResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param base 
 * @param from 
 * @param to 
 * @param results 
 * @param universe 
 */


data class MeanReversionResponse (

    @Json(name = "base")
    val base: kotlin.String,

    @Json(name = "from")
    val from: kotlin.String,

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "results")
    val results: kotlin.collections.List<MeanReversionResponseResultsInner>,

    @Json(name = "universe")
    val universe: MeanReversionResponse.Universe? = null

) {

    /**
     * 
     *
     * Values: liquid,majors
     */
    @JsonClass(generateAdapter = false)
    enum class Universe(val value: kotlin.String) {
        @Json(name = "liquid") liquid("liquid"),
        @Json(name = "majors") majors("majors");
    }

}

