/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param score 
 * @param deviationPct 
 * @param reversionFrequency 
 * @param halfLifeDays 
 * @param note 
 */


data class MeanReversionResponseResultsInner (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "score")
    val score: java.math.BigDecimal?,

    @Json(name = "deviationPct")
    val deviationPct: java.math.BigDecimal?,

    @Json(name = "reversionFrequency")
    val reversionFrequency: java.math.BigDecimal?,

    @Json(name = "halfLifeDays")
    val halfLifeDays: java.math.BigDecimal?,

    @Json(name = "note")
    val note: kotlin.String? = null

) {


}

