/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.HistoryAnalysisResponseResultsInnerStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param country 
 * @param startYear 
 * @param endYear 
 * @param startFactor 
 * @param endFactor 
 * @param changePct 
 * @param projected 
 * @param stats 
 * @param series 
 * @param note 
 */


data class PppAnalysisResponseResultsInner (

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "startYear")
    val startYear: java.math.BigDecimal,

    @Json(name = "endYear")
    val endYear: java.math.BigDecimal,

    @Json(name = "startFactor")
    val startFactor: java.math.BigDecimal?,

    @Json(name = "endFactor")
    val endFactor: java.math.BigDecimal?,

    @Json(name = "changePct")
    val changePct: java.math.BigDecimal?,

    @Json(name = "projected")
    val projected: kotlin.Boolean,

    @Json(name = "stats")
    val stats: HistoryAnalysisResponseResultsInnerStats? = null,

    @Json(name = "series")
    val series: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null,

    @Json(name = "note")
    val note: kotlin.String? = null

) {


}

