/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.PppAnalysisResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param from 
 * @param to 
 * @param mode 
 * @param stats 
 * @param results 
 * @param sort 
 */


data class PppAnalysisResponse (

    @Json(name = "from")
    val from: java.math.BigDecimal,

    @Json(name = "to")
    val to: java.math.BigDecimal,

    @Json(name = "mode")
    val mode: PppAnalysisResponse.Mode,

    @Json(name = "stats")
    val stats: kotlin.Boolean,

    @Json(name = "results")
    val results: kotlin.collections.List<PppAnalysisResponseResultsInner>,

    @Json(name = "sort")
    val sort: PppAnalysisResponse.Sort? = null

) {

    /**
     * 
     *
     * Values: compare,movers
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "compare") compare("compare"),
        @Json(name = "movers") movers("movers");
    }
    /**
     * 
     *
     * Values: increased,decreased
     */
    @JsonClass(generateAdapter = false)
    enum class Sort(val value: kotlin.String) {
        @Json(name = "increased") increased("increased"),
        @Json(name = "decreased") decreased("decreased");
    }

}

