/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param date 
 * @param base 
 * @param rates 
 * @param requestedDate 
 * @param asOf 
 */


data class RatesResponse (

    @Json(name = "date")
    val date: kotlin.String,

    @Json(name = "base")
    val base: RatesResponse.Base,

    @Json(name = "rates")
    val rates: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>,

    @Json(name = "requestedDate")
    val requestedDate: kotlin.String? = null,

    @Json(name = "asOf")
    val asOf: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: USD
     */
    @JsonClass(generateAdapter = false)
    enum class Base(val value: kotlin.String) {
        @Json(name = "USD") USD("USD");
    }

}

