/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param base 
 * @param year 
 * @param propertyValues 
 */


data class RatesByBaseResponsePpp (

    @Json(name = "base")
    val base: kotlin.String,

    @Json(name = "year")
    val year: java.math.BigDecimal,

    @Json(name = "values")
    val propertyValues: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>

) {


}

