/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.RatesByBaseResponsePpp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param base 
 * @param date 
 * @param rates 
 * @param requestedDate 
 * @param asOf 
 * @param ppp 
 */


data class RatesByBaseResponse (

    @Json(name = "base")
    val base: kotlin.String,

    @Json(name = "date")
    val date: kotlin.String,

    @Json(name = "rates")
    val rates: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>,

    @Json(name = "requestedDate")
    val requestedDate: kotlin.String? = null,

    @Json(name = "asOf")
    val asOf: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "ppp")
    val ppp: RatesByBaseResponsePpp? = null

) {


}

