/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.models

import com.currencycore.sdk.models.VolatilityResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param base 
 * @param from 
 * @param to 
 * @param mode 
 * @param basis 
 * @param results 
 * @param sort 
 * @param universe 
 */


data class VolatilityResponse (

    @Json(name = "base")
    val base: kotlin.String,

    @Json(name = "from")
    val from: kotlin.String,

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "mode")
    val mode: VolatilityResponse.Mode,

    @Json(name = "basis")
    val basis: VolatilityResponse.Basis,

    @Json(name = "results")
    val results: kotlin.collections.List<VolatilityResponseResultsInner>,

    @Json(name = "sort")
    val sort: VolatilityResponse.Sort? = null,

    @Json(name = "universe")
    val universe: VolatilityResponse.Universe? = null

) {

    /**
     * 
     *
     * Values: compare,ranking
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "compare") compare("compare"),
        @Json(name = "ranking") ranking("ranking");
    }
    /**
     * 
     *
     * Values: annualizedMinusDaily
     */
    @JsonClass(generateAdapter = false)
    enum class Basis(val value: kotlin.String) {
        @Json(name = "annualized-daily") annualizedMinusDaily("annualized-daily");
    }
    /**
     * 
     *
     * Values: stable,volatile
     */
    @JsonClass(generateAdapter = false)
    enum class Sort(val value: kotlin.String) {
        @Json(name = "stable") stable("stable"),
        @Json(name = "volatile") volatile("volatile");
    }
    /**
     * 
     *
     * Values: liquid,majors
     */
    @JsonClass(generateAdapter = false)
    enum class Universe(val value: kotlin.String) {
        @Json(name = "liquid") liquid("liquid"),
        @Json(name = "majors") majors("majors");
    }

}

