/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.currencycore.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.currencycore.sdk.apis.CurrencyCoreApi
import com.currencycore.sdk.models.AiResponse
import com.currencycore.sdk.models.ApiError
import com.currencycore.sdk.models.ConvertResponse
import com.currencycore.sdk.models.CorrelationResponse
import com.currencycore.sdk.models.CountriesResponseInner
import com.currencycore.sdk.models.CurrenciesResponseInner
import com.currencycore.sdk.models.DrawdownResponse
import com.currencycore.sdk.models.HistoryAnalysisResponse
import com.currencycore.sdk.models.HistoryResponse
import com.currencycore.sdk.models.MeanReversionResponse
import com.currencycore.sdk.models.PppAnalysisResponse
import com.currencycore.sdk.models.RatesByBaseResponse
import com.currencycore.sdk.models.RatesResponse
import com.currencycore.sdk.models.SafeHavenResponse
import com.currencycore.sdk.models.VolatilityResponse

class CurrencyCoreApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrencyCoreApi
        //val apiInstance = CurrencyCoreApi()

        // to test ai
        should("test ai") {
            // uncomment below to test ai
            //val q : kotlin.String = Convert 50 euro to indian rupees // kotlin.String | A natural-language question, e.g. \"Convert 50 euro to indian rupees\" or \"What's the USD to EUR rate today?\".
            //val result : AiResponse = apiInstance.ai(q)
            //result shouldBe ("TODO")
        }

        // to test convert
        should("test convert") {
            // uncomment below to test convert
            //val from : kotlin.String = USD // kotlin.String | Source currency (ISO 4217), e.g. USD. For PPP (ppp=true) pair it with a country as CUR:COUNTRY, e.g. USD:USA.
            //val to : kotlin.String = EUR,INR // kotlin.String | One or more target currencies, comma-separated, e.g. EUR,INR (max 25). For PPP use CUR:COUNTRY pairs, e.g. EUR:DEU,INR:IND.
            //val amount : java.math.BigDecimal = 100 // java.math.BigDecimal | Amount to convert. Optional, defaults to 1 (so each result equals the rate).
            //val ppp : kotlin.Boolean = false // kotlin.Boolean | When true, apply a PPP adjustment. Every currency must then carry a country code.
            //val date : kotlin.String = date_example // kotlin.String | Rate date in YYYY-MM-DD (UTC). Must not be in the future. Defaults to latest.
            //val result : ConvertResponse = apiInstance.convert(from, to, amount, ppp, date)
            //result shouldBe ("TODO")
        }

        // to test correlation
        should("test correlation") {
            // uncomment below to test correlation
            //val currencies : kotlin.String = GBP,CHF,SEK // kotlin.String | Comma-separated currencies to correlate with `base`, e.g. GBP,CHF,SEK.
            //val base : kotlin.String = EUR // kotlin.String | Reference currency to correlate against (3-letter ISO 4217). Defaults to USD (a non-USD base is more meaningful).
            //val from : kotlin.String = from_example // kotlin.String | Window start YYYY-MM-DD (UTC). Defaults to 365 days before `to`.
            //val to : kotlin.String = to_example // kotlin.String | Window end YYYY-MM-DD (UTC). Defaults to today.
            //val result : CorrelationResponse = apiInstance.correlation(currencies, base, from, to)
            //result shouldBe ("TODO")
        }

        // to test countries
        should("test countries") {
            // uncomment below to test countries
            //val result : kotlin.collections.List<CountriesResponseInner> = apiInstance.countries()
            //result shouldBe ("TODO")
        }

        // to test currencies
        should("test currencies") {
            // uncomment below to test currencies
            //val result : kotlin.collections.List<CurrenciesResponseInner> = apiInstance.currencies()
            //result shouldBe ("TODO")
        }

        // to test drawdown
        should("test drawdown") {
            // uncomment below to test drawdown
            //val currency : kotlin.String = EUR // kotlin.String | Currency to measure (3-letter ISO 4217), or a comma-separated list. OMIT to RANK the liquid set by drawdown.
            //val base : kotlin.String = USD // kotlin.String | Base currency to measure against (3-letter ISO 4217). Defaults to USD.
            //val from : kotlin.String = from_example // kotlin.String | Window start YYYY-MM-DD (UTC). Defaults to 365 days before `to`.
            //val to : kotlin.String = to_example // kotlin.String | Window end YYYY-MM-DD (UTC). Defaults to today.
            //val sort : kotlin.String = deepest // kotlin.String | Ranking direction: deepest (largest decline first, default) or recovery (fastest recovery first).
            //val universe : kotlin.String = liquid // kotlin.String | Ranking universe: liquid (default) or majors.
            //val limit : java.math.BigDecimal = 10 // java.math.BigDecimal | Ranking: how many to return (default 10, max 50).
            //val result : DrawdownResponse = apiInstance.drawdown(currency, base, from, to, sort, universe, limit)
            //result shouldBe ("TODO")
        }

        // to test history
        should("test history") {
            // uncomment below to test history
            //val currency : kotlin.String = INR // kotlin.String | The currency whose history to fetch (3-letter ISO 4217), e.g. INR. One currency per call.
            //val from : kotlin.String = from_example // kotlin.String | Start date YYYY-MM-DD (UTC). Defaults to 7 days before `to`.
            //val to : kotlin.String = to_example // kotlin.String | End date YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today.
            //val base : kotlin.String = USD // kotlin.String | Base currency the rates are expressed against (3-letter ISO 4217). Defaults to USD.
            //val interval : kotlin.String = daily // kotlin.String | Aggregation: daily (default), weekly, monthly, or yearly. Coarser intervals average the daily rates per bucket (weekly key = the week's Monday, monthly = YYYY-MM, yearly = YYYY).
            //val result : HistoryResponse = apiInstance.history(currency, from, to, base, interval)
            //result shouldBe ("TODO")
        }

        // to test historyAnalysis
        should("test historyAnalysis") {
            // uncomment below to test historyAnalysis
            //val base : kotlin.String = USD // kotlin.String | Currency everything is measured against (3-letter ISO 4217). Defaults to USD.
            //val currencies : kotlin.String = GBP,EUR,AED // kotlin.String | Comma-separated currencies to compare, e.g. GBP,EUR,AED. OMIT to rank ALL currencies vs base ('movers' mode).
            //val from : kotlin.String = from_example // kotlin.String | Window start YYYY-MM-DD (UTC). Defaults to 20 years (2 decades) before `to`. See `period` for a shorthand.
            //val to : kotlin.String = to_example // kotlin.String | Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today.
            //val period : kotlin.String = 10y // kotlin.String | Relative window shorthand for `from`: e.g. 10y, 6m, 30d, ytd, max. Ignored if `from` is given.
            //val sort : kotlin.String = strengthened // kotlin.String | Movers ranking: strengthened (default) or weakened.
            //val assetClass : kotlin.String = fiat // kotlin.String | Movers universe: fiat (default, the liquid tradeable currencies), metals (XAU/XAG/XPT/XPD), or all (every currency incl. illiquid/frontier). fiat excludes metals/synthetics + illiquid frontier codes; redenomination artifacts are always dropped.
            //val limit : java.math.BigDecimal = 10 // java.math.BigDecimal | Movers: how many top results to return (default 10, max 200).
            //val interval : kotlin.String = yearly // kotlin.String | Attach a trend series per named currency: weekly, monthly, or yearly (compare mode only).
            //val stats : kotlin.Boolean = true // kotlin.Boolean | Include min/max/avg over the window per currency. Defaults to true; pass false to skip.
            //val result : HistoryAnalysisResponse = apiInstance.historyAnalysis(base, currencies, from, to, period, sort, assetClass, limit, interval, stats)
            //result shouldBe ("TODO")
        }

        // to test meanReversion
        should("test meanReversion") {
            // uncomment below to test meanReversion
            //val currencies : kotlin.String = EUR,GBP // kotlin.String | Comma-separated currencies to score, e.g. EUR,GBP. OMIT to rank the liquid set.
            //val base : kotlin.String = USD // kotlin.String | Base currency to measure against (3-letter ISO 4217). Defaults to USD.
            //val from : kotlin.String = from_example // kotlin.String | Window start YYYY-MM-DD (UTC). Defaults to ~2 years before `to`.
            //val to : kotlin.String = to_example // kotlin.String | Window end YYYY-MM-DD (UTC). Defaults to today.
            //val limit : java.math.BigDecimal = 10 // java.math.BigDecimal | How many to return (default 10, max 50).
            //val result : MeanReversionResponse = apiInstance.meanReversion(currencies, base, from, to, limit)
            //result shouldBe ("TODO")
        }

        // to test pppAnalysis
        should("test pppAnalysis") {
            // uncomment below to test pppAnalysis
            //val countries : kotlin.String = IND,DEU,USA // kotlin.String | Comma-separated ISO 3166-1 alpha-3 country codes to compare, e.g. IND,DEU,USA. OMIT to rank ALL countries by PPP-factor change ('movers' mode).
            //val from : kotlin.String = from_example // kotlin.String | Window start YEAR (e.g. 2015). Defaults to 10 years before `to`. See `period` for a shorthand.
            //val to : kotlin.String = to_example // kotlin.String | Window end YEAR (e.g. 2024). Defaults to the current year.
            //val period : kotlin.String = 10y // kotlin.String | Relative window shorthand for `from`: e.g. 10y, 20y, max. Ignored if `from` is given.
            //val sort : kotlin.String = increased // kotlin.String | Movers ranking: increased (PPP factor rose most, default) or decreased.
            //val limit : java.math.BigDecimal = 10 // java.math.BigDecimal | Movers: how many top results to return (default 10, max 200).
            //val stats : kotlin.Boolean = true // kotlin.Boolean | Include min/max/avg of the PPP factor over the window per country. Defaults to true; pass false to skip.
            //val result : PppAnalysisResponse = apiInstance.pppAnalysis(countries, from, to, period, sort, limit, stats)
            //result shouldBe ("TODO")
        }

        // to test rates
        should("test rates") {
            // uncomment below to test rates
            //val date : kotlin.String = date_example // kotlin.String | YYYY-MM-DD. Defaults to the latest available date.
            //val result : RatesResponse = apiInstance.rates(date)
            //result shouldBe ("TODO")
        }

        // to test ratesByBase
        should("test ratesByBase") {
            // uncomment below to test ratesByBase
            //val base : kotlin.String = EUR // kotlin.String | Base currency (3-letter ISO 4217), e.g. EUR.
            //val date : kotlin.String = date_example // kotlin.String | YYYY-MM-DD. Defaults to the latest available date.
            //val result : RatesByBaseResponse = apiInstance.ratesByBase(base, date)
            //result shouldBe ("TODO")
        }

        // to test safeHaven
        should("test safeHaven") {
            // uncomment below to test safeHaven
            //val currencies : kotlin.String = CHF,JPY // kotlin.String | Comma-separated currencies to score, e.g. CHF,JPY. OMIT to rank the safe-haven pool (includes gold).
            //val base : kotlin.String = USD // kotlin.String | Base currency to measure against (3-letter ISO 4217). Defaults to USD.
            //val from : kotlin.String = from_example // kotlin.String | Window start YYYY-MM-DD (UTC). Defaults to 2007-01-01 (spans the 2008 crisis + COVID).
            //val to : kotlin.String = to_example // kotlin.String | Window end YYYY-MM-DD (UTC). Defaults to today.
            //val limit : java.math.BigDecimal = 10 // java.math.BigDecimal | How many to return (default 10, max 50).
            //val result : SafeHavenResponse = apiInstance.safeHaven(currencies, base, from, to, limit)
            //result shouldBe ("TODO")
        }

        // to test volatility
        should("test volatility") {
            // uncomment below to test volatility
            //val currency : kotlin.String = EUR // kotlin.String | Currency to measure (3-letter ISO 4217), or a comma-separated list to compare. OMIT to RANK the liquid-currency set by stability.
            //val base : kotlin.String = USD // kotlin.String | Base currency to measure against (3-letter ISO 4217). Defaults to USD.
            //val from : kotlin.String = from_example // kotlin.String | Window start YYYY-MM-DD (UTC). Defaults to 365 days before `to`.
            //val to : kotlin.String = to_example // kotlin.String | Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today.
            //val sort : kotlin.String = stable // kotlin.String | Ranking direction: stable (least volatile first, default) or volatile.
            //val universe : kotlin.String = liquid // kotlin.String | Ranking universe: liquid (default, broad set) or majors (USD/EUR/GBP/JPY/CHF/CAD/AUD/NZD). Use majors for 'most volatile major pair'.
            //val limit : java.math.BigDecimal = 10 // java.math.BigDecimal | Ranking: how many to return (default 10, max 50).
            //val result : VolatilityResponse = apiInstance.volatility(currency, base, from, to, sort, universe, limit)
            //result shouldBe ("TODO")
        }

    }
}
